logging:
    level:
        blog: WARN
        org: WARN
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${DB_PASSWORD}
        url: jdbc:mysql://localhost:3306/car_repair_service?createDatabaseIfNotExist=true
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
