spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mobilelele-project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        open-in-view: false
    sql:
        init:
            mode: never
#            mode: always
logging:
    level:
#      org.hibernate.orm.jdbc.bind: trace
      org.hibernate.type: trace
#      org.hibernate.stat: debug
      org.hibernate:sql: debug
#      org.hibernate.type.descriptor.sql.BasicBinder: trace